services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinder_ai
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend-go
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  ml-service:
    build: ./ml-service-python
    ports:
      - "5000:5000"
    depends_on:
      - postgres